import { z } from "zod";

/** Shared ISO-8601 timestamp shape used across application contracts. */
export const isoTimestampSchema = z.string().datetime({ offset: true });

/**
 * A calendar date (`YYYY-MM-DD`), used for due dates. Stored as a plain date rather
 * than a timestamp: a due date names a day, not an instant, so it must not shift
 * across timezones. Rejects strings that are not real calendar dates.
 */
export const isoDateSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "must be an ISO-8601 date (YYYY-MM-DD)")
  .refine((value) => {
    const [year, month, day] = value.split("-").map(Number) as [number, number, number];
    const date = new Date(Date.UTC(year, month - 1, day));
    return (
      date.getUTCFullYear() === year &&
      date.getUTCMonth() === month - 1 &&
      date.getUTCDate() === day
    );
  }, "must be a valid calendar date");

/** UUIDv7 identifiers are generated by the application and shaped like any UUID. */
export const uuidSchema = z.string().uuid();

/**
 * Minimal user shape safe to embed in lists (board summaries, member rosters,
 * invitation previews). Never includes email, password, tokens, or hashes.
 */
export const userPreviewSchema = z
  .object({
    id: uuidSchema,
    name: z.string().min(1),
    avatarSeed: z.string().min(1),
  })
  .strict();

export type UserPreview = z.infer<typeof userPreviewSchema>;
