import { z } from "zod";

/** Shared ISO-8601 timestamp shape used across application contracts. */
export const isoTimestampSchema = z.string().datetime({ offset: true });

/** UUIDv7 identifiers are generated by the application and shaped like any UUID. */
export const uuidSchema = z.string().uuid();

/**
 * Minimal user shape safe to embed in lists (board summaries, member rosters,
 * invitation previews). Never includes email, password, tokens, or hashes.
 */
export const userPreviewSchema = z
  .object({
    id: uuidSchema,
    name: z.string().min(1),
    avatarSeed: z.string().min(1),
  })
  .strict();

export type UserPreview = z.infer<typeof userPreviewSchema>;
